apiVersion: v1
kind: Service
metadata:
  name: devcamper-webapi-service
  namespace: devcamper-namespace
spec:
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  selector:
    app: devcamper-webapi

---
# Web API Nodeport service was created just to access the web API from the host machine.

apiVersion: v1
kind: Service
metadata:
  name: devcamper-webapi-nodeport-service
  namespace: devcamper-namespace
spec:
  type: NodePort
  selector:
    app: devcamper-webapi
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 32000

---
# Web API Loadbalancer service was created just to access the web API from the host machine.

apiVersion: v1
kind: Service
metadata:
  name: devcamper-webapi-loadbalancer-service
  namespace: devcamper-namespace
spec:
  type: LoadBalancer
  selector:
    app: devcamper-webapi
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
