apiVersion: v1
kind: ConfigMap
metadata:
  name: devcamper-webapi-configmap
  namespace: devcamper-namespace
data:
  mongodb_host: 'devcamper-db-clusterip-service'
  mongodb_port: '27017'
  mongodb_db_name: 'devcamper-db'
  mongodb_db_params: 'authSource=admin'
  geocoder_provider: 'mapquest'
  rate_limit_window: '100'
  rate_limit_max: '1000'
  jwt_cookie_expire: '30'
  file_upload_path: './public/uploads'
  max_file_upload: '1000000'
