apiVersion: v1
kind: Service
metadata:
  name: devcamper-webapi-service
  namespace: devcamper-namespace
spec:
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  selector:
    app: devcamper-webapi
