apiVersion: v1
kind: Service
metadata:
  name: devcamper-webapi-nodeport-service
  namespace: devcamper-namespace
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 32018
  selector:
    app: devcamper-webapi
