apiVersion: v1
kind: Service
metadata:
  name: devcamper-webapi-loadbalancer-service
  namespace: devcamper-namespace
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 5000
  selector:
    app: devcamper-webapi
