apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: devcamper-pvc
  namespace: devcamper-namespace
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: azure-disk
