apiVersion: v1
kind: Service
metadata:
  name: devcamper-db-loadbalancer-service
  namespace: devcamper-namespace
spec:
  selector:
    app: devcamper-db
  ports:
    - name: mongodb
      port: 27017
      targetPort: 27017
  type: LoadBalancer
