apiVersion: v1
kind: PersistentVolume
metadata:
  name: devcamper-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  azureDisk:
    kind: Managed
    diskName: devcamper-storage-disk
    diskURI: <ENTER_AZURE_DISK_URI_HERE>
  storageClassName: azure-disk
