apiVersion: v1
kind: PersistentVolume
metadata:
  name: devcamper-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  azureDisk:
    kind: Managed
    diskName: devcamper-storage-disk
    diskURI: /subscriptions/dcf53c44-1b3a-421b-a2e2-923444b13b6a/resourceGroups/DEVCAMPER-RG/providers/Microsoft.Compute/disks/devcamper-storage-disk
  storageClassName: azure-disk
