apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: devcamper-pvc
  namespace: devcamper-namespace
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: '' # Ensure no StorageClass is used
