apiVersion: v1
kind: Service
metadata:
  name: devcamper-db-service
  namespace: devcamper-namespace
spec:
  type: ClusterIP
  selector:
    app: devcamper-db
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017

---
# Database Nodeport service was created just to access the database from the host machine. It is not recommended to use this service in production.

apiVersion: v1
kind: Service
metadata:
  name: devcamper-db-nodeport-service
  namespace: devcamper-namespace
spec:
  type: NodePort
  selector:
    app: devcamper-db
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
      nodePort: 32017
