apiVersion: v1
kind: Service
metadata:
  name: devcamper-webapp-loadbalancer-service
  namespace: devcamper-namespace
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 3000
  selector:
    app: devcamper-webapp
