apiVersion: v1
kind: Service
metadata:
  name: devcamper-webapp-nodeport-service
  namespace: devcamper-namespace
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 32001
  selector:
    app: devcamper-webapp
