apiVersion: v1
kind: Service
metadata:
  name: devcamper-webapp-service
  namespace: devcamper-namespace
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  selector:
    app: devcamper-webapp
