apiVersion: v1
kind: ConfigMap
metadata:
  name: devcamper-webapp-configmap
  namespace: devcamper-namespace
data:
  config.json: |
    {
      "react_app_devcamper_base_api_uri": "http://devcamper.webapi/api/v1"
    }
