apiVersion: v1
kind: ConfigMap
metadata:
  name: devcamper-webapp-configmap
  namespace: devcamper-namespace
data:
  react_app_devcamper_base_api_dev_uri: 'http://localhost:5000/api/v1'
  react_app_devcamper_base_api_prod_uri: 'http://devcamper.webapi/api/v1'
