apiVersion: apps/v1
kind: Deployment
metadata:
  name: devcamper-webapp-deployment
  namespace: devcamper-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devcamper-webapp
  template:
    metadata:
      labels:
        app: devcamper-webapp
    spec:
      containers:
        - name: devcamper-webapp-container
          image: prasadhonrao/devcamper-webapp:latest
          ports:
            - containerPort: 3000
          env:
            - name: REACT_APP_DEVCAMPER_BASE_API_URI
              valueFrom:
                configMapKeyRef:
                  name: devcamper-webapp-configmap
                  key: react_app_devcamper_base_api_uri
          resources:
            limits:
              memory: '2Gi'
              cpu: '2'
            requests:
              memory: '1Gi'
              cpu: '1'
