apiVersion: apps/v1
kind: Deployment
metadata:
  name: devcamper-webapp-deployment
  namespace: devcamper-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devcamper-webapp
  template:
    metadata:
      labels:
        app: devcamper-webapp
    spec:
      containers:
        - name: devcamper-webapp-container
          image: prasadhonrao/devcamper-webapp:latest
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: 'production'
          resources:
            limits:
              memory: '2Gi'
              cpu: '2'
            requests:
              memory: '1Gi'
              cpu: '1'
          volumeMounts:
            - name: config-volume
              mountPath: /app/build/config/config.json # /app/build is the path where the app is deployed. Check the Dockerfile of the webapp where node server is monitoring build folder and app is the working directory. Ensures that the mountPath is set to the full path where the config.json file should be placed.
              subPath: devcamper-config-json # this is the key in the configmap data section
      volumes:
        - name: config-volume
          configMap:
            name: devcamper-webapp-configmap
