name: API - DEV - Deploy to Azure

on:
  workflow_dispatch:

env:
  DOCKER_IMAGE: prasadhonrao/devcamper-webapi
  AZURE_WEBAPP_NAME: devcamper-webapi

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Log in to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_SERVICE_PRINCIPAL }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          images: '${{ env.DOCKER_IMAGE }}:latest'

  notify:
    runs-on: ubuntu-latest
    needs: deploy
    if: always()

    steps:
      - name: Send email notification
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.GMAIL_USERNAME }}
          password: ${{ secrets.GMAIL_PASSWORD }}
          subject: '${{ job.status }}: DevCamper API Deployment'
          body: |
            The deployment has ${{ job.status }}!
            Repository: ${{ github.repository }}
            Branch: ${{ github.ref }}
            Commit: ${{ github.sha }}
            Author: ${{ github.actor }}
            Workflow: ${{ github.workflow }}
            Job: ${{ github.job }}
            Run ID: ${{ github.run_id }}
            Run Number: ${{ github.run_number }}
            Logs: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          to: ${{ secrets.NOTIFY_EMAIL }}
          from: ${{ secrets.GMAIL_USERNAME }}
