name: API - Workflow

on:
  push:
    branches:
      - main
    paths:
      - 'api/**'
  pull_request:
    branches:
      - main
    paths:
      - 'api/**'
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          cd api
          npm install

      - name: Upload code and dependencies
        uses: actions/upload-artifact@v3
        with:
          name: code-and-dependencies
          path: |
            api/
            !api/node_modules/

  lint:
    runs-on: ubuntu-latest
    needs: setup

    steps:
      - name: Download code and dependencies
        uses: actions/download-artifact@v3
        with:
          name: code-and-dependencies
          path: .

      - name: Run linter
        run: |
          cd api
          npm run lint

  dependency-check:
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - name: Download code and dependencies
        uses: actions/download-artifact@v3
        with:
          name: code-and-dependencies
          path: .

      - name: Run dependency check
        run: |
          cd api
          npm audit

  security:
    runs-on: ubuntu-latest
    needs: dependency-check
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - name: Download code and dependencies
        uses: actions/download-artifact@v3
        with:
          name: code-and-dependencies
          path: .

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: javascript

      - name: Autobuild
        uses: github/codeql-action/autobuild@v2

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2

  test:
    runs-on: ubuntu-latest
    needs: security

    steps:
      - name: Download code and dependencies
        uses: actions/download-artifact@v3
        with:
          name: code-and-dependencies
          path: .

      - name: Run tests
        run: |
          cd api
          npm test

  code-coverage:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Download code and dependencies
        uses: actions/download-artifact@v3
        with:
          name: code-and-dependencies
          path: .

      - name: Run tests with coverage
        run: |
          cd api
          npm run test -- --coverage

      - name: Upload coverage report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: api/coverage

  deploy:
    runs-on: ubuntu-latest
    needs: code-coverage

    steps:
      - name: Download code and dependencies
        uses: actions/download-artifact@v3
        with:
          name: code-and-dependencies
          path: .

      - name: Deploy
        run: |
          # Add your deployment steps here
          echo "Deploying the application..."
